spring:
  application:
    name: cloudit
  datasource:
    url: jdbc:mysql://localhost:3307/db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8085
logging:
  level:
    org.springframework.security: TRACE